
using System;
using System.Runtime.CompilerServices;

namespace MP.Random
{
    /// <summary>
    /// Defines generic extension methods for the <see cref="IRandomSource"/> interface.
    /// </summary>
    public static class IRandomSourceExtensions
    {
        // Precomputed significands for System.Single and System.Double
        // Avoids computing them upon calling NextSingle/Double.
        private const System.Double NEXTDOUBLESIGNIFICAND = 1.0d / (1ul << 53);
        private const System.Single NEXTSINGLESIGNIFICAND = 1.0f / (1u << 24);

        /// <summary>
        /// Generates a new 32-bit random signed integer.
        /// </summary>
        /// <param name="rng">The random number generator to use.</param>
        /// <returns>The integer produced.</returns>
        public static System.Int32 NextInt32(this IRandomSource rng) => (rng.Next() >> 33).ToInt32();

        /// <summary>
        /// Generates a new 16-bit random unsigned integer.
        /// </summary>
        /// <param name="rng">The random number generator to use.</param>
        /// <returns>The integer produced.</returns>
        public static System.UInt16 NextUInt16(this IRandomSource rng) => (rng.Next() >> 48).ToUInt16();

        /// <summary>
        /// Generates a new 64-bit random signed integer.
        /// </summary>
        /// <param name="rng">The random number generator to use.</param>
        /// <returns>The integer produced.</returns>
        public static System.Int64 NextInt64(this IRandomSource rng) => (rng.Next() >> 1).ToInt64();

        /// <summary>
        /// Generates a new 16-bit random signed integer.
        /// </summary>
        /// <param name="rng">The random number generator to use.</param>
        /// <returns>The integer produced.</returns>
        public static System.Int16 NextInt16(this IRandomSource rng) => (rng.Next() >> 49).ToInt16();

        /// <summary>
        /// Generates a new 32-bit random unsigned integer.
        /// </summary>
        /// <param name="rng">The random number generator to use.</param>
        /// <returns>The integer produced.</returns>
        public static System.UInt32 NextUInt32(this IRandomSource rng) => (rng.Next() >> 32).ToUInt32();

        /// <summary>
        /// Computes a <see cref="System.Boolean"/> using the <see cref="NextInt16(IRandomSource)"/> method and with a special formula
        /// to create a randomly-generated boolean.
        /// </summary>
        /// <param name="rng">The random number generator to use.</param>
        /// <returns>A randomly-generated boolean.</returns>
        // We could agressively inline it but we do not know the contents of Next() in advance
        public static System.Boolean NextBoolean(this IRandomSource rng) => ((rng.Next() | 4) & 1) == 0; // Check LSB of the result and determine what to return

        /// <summary>
        /// Returns a randomly-generated byte.
        /// </summary>
        /// <param name="rng">The random number generator to use.</param>
        /// <returns>A newly generated random byte.</returns>
        public static System.Byte NextByte(this IRandomSource rng) => (rng.Next() >> 56).ToByte();

        /// <summary>
        /// Returns a double-precision floating number, ranging from 0 to 1.
        /// </summary>
        /// <param name="rng">The random number generator to use.</param>
        /// <returns>A newly generated double-precision floating number.</returns>
        // http://prng.di.unimi.it/ comments about the doubles:
        // A standard double (64-bit) floating-point number in IEEE floating point format has 52 bits of significand, plus an implicit bit at the left of the significand.
        //  Thus, the representation can actually store numbers with 53 significant binary digits.
        //  Because of this fact, in C99 a 64-bit unsigned integer x should be converted to a 64-bit double using the expression:
        //  (x >> 11) * 0x1.0p-53
        // mdcdi1315: Pre-compute 0x1.0p-53 value to earn additional perf by just loading it's result
        public static System.Double NextDouble(this IRandomSource rng) => (rng.Next() >> 11) * NEXTDOUBLESIGNIFICAND;

        /// <summary>
        /// Returns a single-precision floating number, ranging from 0 to 1.
        /// </summary>
        /// <param name="rng">The random number generator to use.</param>
        /// <returns>A newly generated single-precision floating number.</returns>
        public static System.Double NextSingle(this IRandomSource rng) => (rng.Next() >> 40) * NEXTSINGLESIGNIFICAND;

        /// <summary>
        /// Fills an array with random bytes using the random number generator specified in <paramref name="rng"/>.
        /// </summary>
        /// <param name="rng">The random number generator to use.</param>
        /// <param name="bytes">The array instance to fill with bytes.</param>
        /// <param name="offset">The offset inside the array to start filling with bytes.</param>
        /// <param name="count">The number of bytes to fill into the array.</param>
        /// <exception cref="ArgumentNullException"><paramref name="bytes"/> were null.</exception>
        /// <exception cref="ArgumentException"><paramref name="offset"/> or <paramref name="count"/> were less than zero.</exception>
        /// <exception cref="ArgumentOutOfRangeException"><paramref name="count"/> - <paramref name="offset"/> result was larger than the array length.</exception>
        public static void NextBytes(this IRandomSource rng, System.Byte[] bytes, System.Int32 offset, System.Int32 count)
        {
            if (bytes is null) { throw new ArgumentNullException(nameof(bytes)); }
            if (offset < 0 || count < 0) { throw new ArgumentException("offset or count must not be less than zero."); }
            if (count - offset > bytes.Length) { throw new ArgumentOutOfRangeException("count - offset must be less than the array length.", innerException: null); }
            // We need 'count' bytes to be copied to 'bytes'.
            // + 1 to avoid non-divisible by eight cases when the count is such (if happened we could get out of bounds when performing the CopyBlockUnaligned call)
            System.UInt64[] rands = new System.UInt64[(count / sizeof(System.UInt64)) + (((count % 8) == 0) ? 0 : 1)];
            // Generate all the required random numbers
            for (System.Int32 I = 0; I < rands.Length; I++) { rands[I] = rng.Next(); }
            // Unsafe copy to the actual array
            Unsafe.CopyBlockUnaligned(ref bytes[offset] , ref Unsafe.As<System.UInt64 , System.Byte>(ref rands[0]) , count.ToUInt32());
        }

        /// <summary>
        /// Fills an array with random bytes using the random number generator specified in <paramref name="rng"/>.
        /// </summary>
        /// <param name="rng">The random number generator to use.</param>
        /// <param name="bytes">The array instance to fill with bytes.</param>
        /// <exception cref="ArgumentNullException"><paramref name="bytes"/> were null.</exception>
        public static void NextBytes(this IRandomSource rng, System.Byte[] bytes) => NextBytes(rng, bytes, 0, bytes.Length);

        /// <summary>Generates a new random UTF16-LE character.</summary>
        /// <param name="rng">The random number generator to use.</param>
        /// <returns>The random character that was generated by <paramref name="rng"/>.</returns>
        public static System.Char NextChar(this IRandomSource rng) => NextUInt16(rng).ToChar();

        /// <summary>
        /// Produces a random value that is inside the range specified by the <paramref name="minimum"/> and <paramref name="maximum"/> parameters.
        /// </summary>
        /// <param name="rng">The random number generator to use.</param>
        /// <param name="maximum">The maximum value that is acceptable to be returned.</param>
        /// <param name="minimum">The minimum value that is acceptable to be returned.</param>
        /// <returns>A new random value that is inside the range specified.</returns>
        /// <exception cref="ArgumentException"><paramref name="minimum"/> was greater or equal than <paramref name="maximum"/>.</exception>
        public static System.Int32 NextInRange(this IRandomSource rng, System.Int32 minimum, System.Int32 maximum)
        {
            if (minimum >= maximum) { throw new ArgumentException("minimum must always be less than maximum"); }
            System.Int32 result;
            // The below loop executes 'until the number is in range'.
            while ((result = NextInt32(rng)) < minimum || result > maximum) ;
            return result;
        }
    }
}