
using System;
using Microsoft.CodeAnalysis;
using System.Collections.Generic;

namespace MP.AbstractionsLib.Analyzer.COMSourceGeneration
{
    public sealed partial class DecodedCOMInterface
    {
        public string IID;
        public Method[] Methods;
        public string FriendlyName;
        public string EnclosedNamespace; // Maybe null.
        // Defines the namespaced type imports when resolving aliased types.
        // Used only when custom types do exist as well, and is used only during COM INT generation.
        // If null, it means that the instance was generated by C#.
        public string[] NamespacedImports;
        public ParsedPartialTypeInformation BaseType;

        public sealed class Method
        {
            public string Name;
            public MethodArgument[] Arguments;
            public ParsedPartialTypeInformation ReturnType;
        }

        public sealed class MethodArgument
        {
            public string Name;
            public ParsedPartialTypeInformation Type;

            public MethodArgument() {}

            public MethodArgument(IParameterSymbol p) : this()
            {
                Name = p.Name;
                Type = new(p.Type);
            }
        }

        public sealed class ParsedPartialTypeInformation
        {
            public string QualifiedName;
            public readonly int PointerIndirections;
            
            public ParsedPartialTypeInformation(ITypeSymbol ts)
            {
                ITypeSymbol tgs = ts;
                PointerIndirections = 0;
                while (tgs is IPointerTypeSymbol p) {
                    tgs = p.PointedAtType;
                    PointerIndirections++;
                }
                QualifiedName = tgs.GetFullTypeNameIgnoreErrors();
            }

            public ParsedPartialTypeInformation(System.String s)
            {
                if (s is null) { throw new ArgumentNullException(nameof(s)); }
                PointerIndirections = 0;
                System.Text.StringBuilder sb = new(s.Length);
                System.Boolean not_terminated = true;
                foreach (System.Char c in s)
                {
                    if (not_terminated && ((c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z') || c == '.' || c == '_' || System.Char.IsDigit(c))) {
                        sb.Append(c);
                    } else if (c == '*' && sb.Length > 0) {
                        not_terminated = false;
                        PointerIndirections++;
                    } else {
                        throw new ArgumentException($"The specified type string contains invalid characters: \"{s}\"");
                    }
                }
                QualifiedName = sb.ToString();
            }

            public sealed override string ToString() => String.Concat(QualifiedName, new string('*', PointerIndirections));
        }

        public string FullName
        {
            get {
                if (EnclosedNamespace is null) { 
                    // This type is declared in the global namespace.
                    return String.Concat("global::", FriendlyName);
                } else {
                    return String.Concat(EnclosedNamespace, "." , FriendlyName);
                }
            }
        }

        public static DecodedCOMInterface FromType(ITypeSymbol ts)
        {
            DecodedCOMInterface dc = new();
            if (AnalyzerUtils.HasAttributeWithMetadataName(ts, "MP.Annotations.COMInterfaceGeneratorAttribute", out AttributeData ad))
            {
                if (ad.ConstructorArguments.Length == 0) {
                    return null;
                } else {
                    dc.IID = ad.ConstructorArguments[0].Value as string;
                    if (dc.IID is null) {
                        return null;
                    } else if (ad.ConstructorArguments.Length == 2) {
                        dc.BaseType = new(ad.ConstructorArguments[1].Value as ITypeSymbol);
                    }
                }
            } else {
                return null;
            }
            if (dc.BaseType is null) {
                if (ts.AllInterfaces.Length == 0) {
                    dc.BaseType = null;
                } else {
                    INamedTypeSymbol sym = ts.Interfaces[0];
                    dc.BaseType = new(sym);
                    if (!AnalyzerUtils.HasAttributeWithMetadataName(sym, "MP.Annotations.COMInterfaceAttribute")) {
                        throw new InvalidOperationException($"The specified base interface is not a proper COM Interface: {dc.BaseType}");
                    }
                }
            }
            dc.FriendlyName = ts.Name;
            dc.EnclosedNamespace = ts.ContainingNamespace.GetFullNamespaceName();
            List<Method> methods = new();
            foreach (ISymbol sym in ts.GetMembers())
            {
                Method m;
                MethodArgument[] arguments;
                if (sym is IMethodSymbol ms)
                {
                    m = new();
                    m.Name = ms.Name;
                    m.ReturnType = new(ms.ReturnType);
                    arguments = new MethodArgument[ms.Parameters.Length];
                    for (int I = 0; I < arguments.Length; I++)
                    {
                        arguments[I] = new(ms.Parameters[I]);
                    }
                    m.Arguments = arguments;
                    methods.Add(m);
                }
            }
            dc.NamespacedImports = null;
            dc.Methods = methods.ToArray();
            return dc;
        }
    }
}