
using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace MP.AbstractionsLib.Analyzer.DataStructureGeneration
{
    [Generator(LanguageNames.CSharp)]
    public sealed class MPDataStructureGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterSourceOutput(
                context.SyntaxProvider.ForAttributeWithMetadataName<INamedTypeSymbol>(
                    "MP.IO.DataStructuring.Generation.DataStructureGeneratorAttribute",
                    new(SyntaxNodePredicate),
                    new(SyntaxNodeTransform)
                ),
                new(GenerateData)
            );
        }

        private static System.Boolean SyntaxNodePredicate(SyntaxNode sn, System.Threading.CancellationToken ct) => sn is StructDeclarationSyntax || sn is ClassDeclarationSyntax;

        private static INamedTypeSymbol SyntaxNodeTransform(GeneratorAttributeSyntaxContext gasc, System.Threading.CancellationToken ct)
        {
            ct.ThrowIfCancellationRequested();
            return gasc.TargetSymbol as INamedTypeSymbol;
        }

        private static bool IsUsedForVariableLengthString(StructureFieldData f, List<StructureFieldData> fields, out StructureVariableStringFieldData v)
        {
            string n = f.Name;
            foreach (var field in fields)
            {
                if (field is StructureVariableStringFieldData d && d.FieldLengthProvider == n)
                {
                    v = d;
                    return true;
                }
            }
            v = null;
            return false;
        }

        private static string ConstructTypedNameForWriteVariableString(SpecialType sp) => sp switch
        {
            SpecialType.System_Byte => "Byte",
            SpecialType.System_Int16 => "Short",
            SpecialType.System_Int32 => "Int",
            SpecialType.System_Int64 => "Long",
            SpecialType.System_UInt16 => "UShort",
            SpecialType.System_UInt32 => "UInt",
            SpecialType.System_UInt64 => "ULong",
            _ => null
        };

        private static void GenerateData(SourceProductionContext spc, INamedTypeSymbol sym)
        {
            if (!AnalyzerUtils.ImplementsInterface(sym, "MP.IO.DataStructuring.IDataStructure"))
            {
                spc.ReportDiagnostic(Diagnostic.Create(MPDataStructureGeneratorDiagnosticDescriptors.RULE_6, null, sym.GetFullTypeName()));
                return;
            }

            System.Text.StringBuilder sb = new();

            sb.AppendLine();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// Auto-generated by the MP Data Generator.");
            sb.AppendLine("// Contains definitions for reading/writing structured data - modifications of this may cause instability!");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();

            sb.AppendLine();
            sb.AppendLine("using MP;");
            sb.AppendLine("using MP.IO;");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine("using MP.IO.DataStructuring.Generation;");
            sb.AppendLine();

            string ns = sym.ContainingNamespace.GetFullNamespaceName();

            if (!System.String.IsNullOrEmpty(ns)) {
                sb.AppendFormatLine("namespace {0};", ns);
            }

            sb.AppendLine();
            sb.AppendFormatLine("unsafe partial {0} {1}", sym.IsValueType ? "struct" : "class", sym.Name);
            sb.AppendLine('{');

            // Read Method data generation.

            sb.AppendTabs(1);
            sb.AppendLine("/// <inheritdoc />");
            sb.AppendTabs(1);

            bool extending;
            if (extending = AnalyzerUtils.ExtendsFromAnyAbstractClass(sym)) {
                sb.AppendLine("public override void Load(IDataStreamAccess access)");
            } else {
                sb.AppendLine("public void Load(IDataStreamAccess access)");
            }
            
            sb.AppendTabs(1);
            sb.AppendLine('{');

            List<System.String> methods_to_append = new();
            List<StructureFieldData> fields = StructureFieldData.GetValidFields(sym, new(spc.ReportDiagnostic));

            if (fields is null) { return; }

            foreach (StructureFieldData sfd in fields)
            {
                sb.AppendTabs(2);
                switch (sfd)
                {
                    case FixedBufferFieldData fb:
                        int m_ord = methods_to_append.Count;
                        methods_to_append.Add(fb.GenerateFixedBufferReadMethod(m_ord));
                        sb.AppendFormatLine("ReadFixedBuffer_G{0}(access);", m_ord);
                        break;
                    case StructureFixedStringFieldData sf:
                        sb.AppendFormatLine("{0} = access.ReadString({1}, {2});", sf.Name, sf.Encoding.ToSystemTextEncodingInstance(), sf.Encoding switch { 
                            StringFieldEncoding.ASCII or StringFieldEncoding.UTF8 => sf.Length,
                            StringFieldEncoding.UTF16LE or StringFieldEncoding.UTF16BE => $"sizeof(System.Char) * {sf.Length}",
                            _ => throw new System.NotImplementedException()
                        });
                        break;
                    case EnumStructureFieldData esf:
                        sb.AppendFormatLine("{0} = DataGeneratorHelpers.ReadEnum{1}<{2}>(access);", esf.Name , esf.IsBigEndian ? "BE" : "LE", esf.FieldType.GetFullTypeName());
                        break;
                    case StructureNumericFieldData sn:
                        sn.GenerateReadingCode(sb);
                        break;
                    case StructureVariableStringFieldData vsf:
                        sb.AppendFormatLine("{0} = access.ReadString({1}, {2});", vsf.Name, vsf.Encoding.ToSystemTextEncodingInstance(), vsf.FieldLengthProvider);
                        break;
                    default:
                        sb.AppendFormatLine("{0} = new(); {0}.Load(access);", sfd.Name);
                        break;
                }
            }
            sb.AppendTabs(1);
            sb.AppendLine('}');

            foreach (string m in methods_to_append) { sb.Append(m); }
            methods_to_append.Clear();

            // Write Method data generation.

            sb.AppendTabs(1);
            sb.AppendLine("/// <inheritdoc />");
            sb.AppendTabs(1);

            if (extending) {
                sb.AppendLine("public override void Save(IDataStreamAccess access)");
            } else {
                sb.AppendLine("public void Save(IDataStreamAccess access)");
            }
            
            sb.AppendTabs(1);
            sb.AppendLine('{');

            foreach (StructureFieldData sfd in fields)
            {
                sb.AppendTabs(2);
                switch (sfd)
                {
                    case FixedBufferFieldData fb:
                        int m_ord = methods_to_append.Count;
                        methods_to_append.Add(fb.GenerateFixedBufferWriteMethod(m_ord));
                        sb.AppendFormatLine("WriteFixedBuffer_G{0}(access);", m_ord);
                        break;
                    case StructureFixedStringFieldData sf:
                        sb.AppendFormatLine("DataGeneratorHelpers.WriteFixedLengthString(access, {0}, {1}, {2});", sf.Name, sf.Encoding.ToSystemTextEncodingInstance(), sf.Length);
                        break;
                    case StructureVariableStringFieldData vsf:
                        sb.AppendFormatLine("gen_{0}_stream.DirectCopyToStream(access);", vsf.FieldLengthProvider);
                        sb.AppendTabs(2);
                        sb.AppendFormatLine("gen_{0}_stream = null;", vsf.FieldLengthProvider);
                        break;
                    case EnumStructureFieldData esf:
                        sb.AppendFormatLine("DataGeneratorHelpers.WriteEnum{0}<{1}>(access, {2});", esf.IsBigEndian ? "BE" : "LE", esf.FieldType.GetFullTypeName(), esf.Name);
                        break;
                    case StructureNumericFieldData sn:
                        if (IsUsedForVariableLengthString(sn, fields, out var s_d)) {
                            string s = ConstructTypedNameForWriteVariableString(sn.FieldType.SpecialType);
                            if (s is null) {
                                spc.ReportDiagnostic(Diagnostic.Create(MPDataStructureGeneratorDiagnosticDescriptors.RULE_5, null, sn.Name, s_d.Name));
                                return;
                            }
                            sb.AppendFormatLine(
                                "{3} = DataGeneratorHelpers.PrepareWriteString_VariableLength_{0}({1}, {2}, out var gen_{3}_stream);",
                                s,
                                s_d.Name,
                                s_d.Encoding.ToSystemTextEncodingInstance(),
                                sn.Name
                            );
                            sb.AppendTabs(2);
                        }
                        sn.GenerateWritingCode(sb);
                        break;
                    default:
                        sb.AppendFormatLine("{0} = new(); {0}.Save(access);", sfd.Name);
                        break;
                }
            }

            sb.AppendTabs(1);
            sb.AppendLine('}');

            foreach (string m in methods_to_append) { sb.Append(m); }
            methods_to_append.Clear();

            sb.AppendLine('}');

            spc.AddSource(System.String.Concat(sym.GetFullTypeName(), ".g.cs"), sb.ToString());
        }
    }
}
